# Generated by Django 4.2.11 on 2024-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to='media/image/', verbose_name='картинка')),
                ('coords', models.JSONField(blank=True, default={}, null=True, verbose_name='координаты')),
            ],
        ),
    ]
