# Generated by Django 4.2.11 on 2024-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='картинка'),
        ),
    ]
