# Generated by Django 4.2.11 on 2024-05-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attractions_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractions',
            options={'verbose_name': 'достопримечательность', 'verbose_name_plural': 'достопримечательности'},
        ),
    ]
