# Generated by Django 4.2.11 on 2024-05-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_attractions_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttractionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/image/",
                        verbose_name="картинка",
                    ),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.attractions",
                        verbose_name="картинки",
                    ),
                ),
            ],
            options={
                "verbose_name": "картинка достопримечательности",
                "verbose_name_plural": "картинки достопримечательностей",
            },
        ),
    ]
