# Generated by Django 4.2.11 on 2024-05-11 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_attractionimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attractions",
            name="image",
        ),
    ]
