# Generated by Django 4.2.11 on 2024-05-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_attractionimage_attraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attractionimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/", verbose_name="картинка"
            ),
        ),
    ]
