# Generated by Django 4.2.11 on 2024-05-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_attractionimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attractions",
            name="coords",
        ),
        migrations.AddField(
            model_name="attractions",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="широта",
            ),
        ),
        migrations.AddField(
            model_name="attractions",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="долгота",
            ),
        ),
    ]
