# Generated by Django 4.2.11 on 2024-05-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_attractions_coords_attractions_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractions",
            name="category",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="категории"
            ),
        ),
    ]
